# Generated by Django 5.2.15 on 2026-07-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/defult.jpg', upload_to='blog'),
        ),
    ]
